apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- bpc-networkpolicy.yaml
- bpc-pdb.yaml

patches:
  - path: bpc-deployment.yaml
    target:
      kind: Deployment
      name: bpc